# Generated by Django 5.1.2 on 2024-11-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0002_initial'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='ticket_holders', to='BookingApp.booking'),
        ),
    ]
