# Generated by Django 5.1.2 on 2024-11-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billingAddress',
            field=models.CharField(blank=True, default='Example Street', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creditCardNumber',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isCreditCard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isPaypal',
            field=models.BooleanField(default=False),
        ),
    ]
