# Generated by Django 5.1.2 on 2024-11-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_user_billingaddress_user_creditcardnumber_user_cvv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cvv',
            new_name='credit_card_cvv',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='expirationDate',
            new_name='credit_card_expiration',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creditCardNumber',
            new_name='credit_card_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isCreditCard',
            new_name='has_credit_card',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isPaypal',
            new_name='has_debit_card',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='has_paypal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billingAddress',
        ),
        migrations.AddField(
            model_name='user',
            name='credit_card_billing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='debit_card_billing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='debit_card_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='debit_card_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='debit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
