# Generated by Django 5.1.2 on 2024-11-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0001_initial'),
        ('UserApp', '0003_rename_cvv_user_credit_card_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='UserApp.user'),
        ),
    ]
