# Generated by Django 5.1.2 on 2024-11-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_count',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
