# Generated by Django 5.1.2 on 2024-11-26 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0003_alter_booking_ticket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
