# Generated by Django 5.1.2 on 2024-11-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('release_date', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(max_length=225)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
