# Generated by Django 5.1.2 on 2024-11-09 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(max_length=100),
        ),
    ]
