# Generated by Django 5.1.2 on 2024-11-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
